version: '3.0'

services:
  grafana:
    container_name: 'gpa-openhistorian-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.3.8}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/gpa-openhistorian-datasource
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      
  openhistorian:
    container_name: openhistorian
    image: gridprotectionalliance/openhistorian:v2.8.423
    ports:
      - 8180:8180/tcp
 
